### PR TITLE
Add .rake

### PR DESCRIPTION
**Pull request by bradurani**
Add support for `.rake`

### CODE REVIEW

**Comment by mcasper** [comment]
Love it.

Has it been tested?

**Comment by bradurani** [comment]
No, wasn't even sure how

**Comment by mcasper** [comment]
Overwrite the array in your local vimrc (the suggested way to set custom extensions)

``` Vim
let g:debugger_array = [['\.rake', 'require "pry"; binding.pry']]
```

**Comment by bradurani** [comment]
^ I tried this out and it works!

**Comment by mcasper** [comment]
Awesome!

**Pull request merged**
