### PR TITLE
Add a RemoveAllDebuggers() function

### PR DESCRIPTION
**Pull request by mcasper**
Added a function to remove all matching debuggers in your current file,
and bound it by default to `d` for now.

### CODE REVIEW

**Comment by mcasper** [comment]
/cc @michaelghinrichs @awseward Review appreciated

I bound this to `b` by default, would gladly accept suggestions for a better binding

**Comment by mcasper** [comment]
I'll add docs after you guys chime in

**Comment by karismatic-megafauna** [comment]
awesome! thanks casper! :)

**Comment by karismatic-megafauna** [comment]
looks like it is bound to `d`? am I crazy?

**Comment by mcasper** [comment]
Yep, definitely meant `d` >.< Editing the top comment

**Comment by karismatic-megafauna** [comment]
also, might be good to not add it to a leader and just expose a command that people can use to bind to whatever leader they want. 

What do you both think?
/cc @mcasper @awseward

**Comment by mcasper** [comment]
I'm fairly certain that `nmap` will only map it if the user hasn't defined anything else for that key combination, so the philosophy is that we provide a default mapping, but the RemoveAllDebuggers() function is public and available for mapping

**Comment by karismatic-megafauna** [comment]
ohhhh i had no idea that this is what `nmap` did! 

good call :) ignore me

**Comment by mcasper** [comment]
Actually now that I read more docs I think that's a complete lie, I just think that the user's bindings in their `.vimrc` always supersede Plugin bindings.

So how do we feel about `<Leader>d` being our default binding?

**Comment by karismatic-megafauna** [comment]
i like it!

**Comment by karismatic-megafauna** [comment]
+1

**Comment by awseward** [comment]
`<Leader>d` sounds good to me

**Comment by mcasper** [comment]
Awesome, thanks guys

**Comment by awseward** [comment]
Thank you for doing this!

**Pull request merged**
